include "base-config.conf"

kafka {
  input.topic = "dev.cf.batch.request"
  output.audit.topic = "dev.telemetry.raw"
  output.failed.topic = "dev.cf.batch.failed"
  groupId = "cf-batch-manager-group"
}

task {
  window.shards = 1
  consumer.parallelism = 1
  batch.updater.parallelism = 1
}

threshold.batch.read.size = 1000

