include "base-config.conf"

kafka {
  input.topic = "dev.cf.batch.request"
  audit.progression.topic = "dev.user.enrollment.audit"
  output.audit.topic = "dev.telemetry.raw"
  output.failed.topic = "dev.cf.batch.failed"
  groupId = "cf-batch-manager-group"
}

task {
  window.shards = 1
  consumer.parallelism = 1
  batch.updater.parallelism = 1
}

threshold.batch.read.size = 1000

lms-cassandra {
  keyspace = "dev_hierarchy_store"
  table = "content_hierarchy"
  isMultiDCEnabled = false
}

service {
    lms.basePath = "http://lms-service:9000"
    clEnroll.endpoint = "/private/v1/activity/enroll"
    courseEnroll.endpoint = "/private/v1/course/enroll"
    search.basePath = "http://search-service:9000"
}

batch.create.endpoint {
    course = "/private/v1/course/batch/create"
    cl = "/private/v1/batch/create"
}

entrance.exam.optional.threshold.percent = 100

user-enrolments-cassandra {
  keyspace = "sunbird_courses"
  table = "user_enrolments"
}

sb-collection-cassandra {
  keyspace = "sb_collection_tracking"
  table = "user_enrolments"
}

assessment-aggregator-cassandra {
  keyspace = "sunbird_courses"
  table = "assessment_aggregator"
}

redis {
  host = redis-master
  port = 6379
  database.index = 6
  ttl = 86400
}

es {
  basePath = "http://elasticsearch:9200"
  activityBatch.index = "activity-batch"
}