include "base-config.conf"

kafka {
  input.topic = "dev.cf.batch.request"
  output.audit.topic = "dev.telemetry.raw"
  output.failed.topic = "dev.cf.batch.failed"
  groupId = "cf-batch-manager-group"
}

task {
  window.shards = 1
  consumer.parallelism = 1
  batch.updater.parallelism = 1
}

threshold.batch.read.size = 1000

lms-cassandra {
  keyspace = "dev_hierarchy_store"
  table = "content_hierarchy"
}

service {
    lms.basePath = "http://localhost:9000"
    clEnroll.endpoint = "/v1/activity/enroll"
    courseEnroll.endpoint = "/course/v1/enrol"
}

batch.create.endpoint {
    course = "/private/v1/course/batch/create"
    cl = "/private/v1/batch/create"
}
