include "base-config.conf"

kafka {
  input.topic = "sunbirddev.cf.progress.update.request"
  output.audit.topic = "sunbirddev.cf.progress.audit"
  groupId = "sunbirddev-cf-progress-updater-group"
}

task {
  consumer.parallelism = 1
  parallelism = 2
}

lms-cassandra {
  keyspace = "dev_cf_progress"
  table = "user_cf_progress"
}

threshold.batch.write.size = 10
enable.parent.progress.update = false

# Feature flags
activity.progress.audit.enabled = false
