include "base-config.conf"

kafka {
  input.topic = "sunbirddev.user.enrollment.audit"
  output.audit.topic = "sunbirddev.telemetry.raw"
  output.failed.topic = "sunbirddev.activity.agg.failed"
  output.certissue.topic = "sunbirddev.issue.certificate.request"
  output.enrollment.audit.topic = "sunbirddev.user.enrollment.audit"
  groupId = "sunbirddev-cf-progress-updater-group"
}
task {
  window.shards = "1000"
  checkpointing.interval = "300000"
  checkpointing.pause.between.seconds = "90000"
  restart-strategy.attempts = "3"
  restart-strategy.delay = 240000 # in milli-seconds # on max restarts (3) within 4 min the job will fail.
  consumer.parallelism = "1"
  dedup.parallelism = "1"
  activity.agg.parallelism = "1"
  enrolment.complete.parallelism = "1"
}
lms-cassandra {
  keyspace = "sunbird_courses"
  consumption.table = "user_content_consumption"
  user_activity_agg.table = "user_activity_agg"
  user_enrolments.table = "user_enrolments"
}
redis {
  database {
    relationCache.id = 6
  }
}

enable.parent.progress.update = true

dedup-redis {
  host = "redis-master"
  port = "6379"
  database.index = "13"
  database.expiry = "604800"
}
threshold.batch.read.interval = "60"
threshold.batch.read.size = "1"
threshold.batch.write.size = "10"

activity {
  module.aggs.enabled = true
  input.dedup.enabled = true
  filter.processed.enrolments = "true"
  collection.status.cache.expiry = "3600"
  enrollment.audit.enabled = true
}

service {
  search.basePath = "http://search-service:9000"
}